### ISSUE TITLE
Might Consider Adding Game Version onto !playing

### ISSUE THREAD

**Issue by Komorebiao** [notoriouslogank/mcswitch#18]
I would lightly suggest or recommend adding a <version> field to the !playing like so: !playing<game? <field> <value> <value>

Ex: of command !playing "Minecraft" "Server IP" "*Server IP" "Version"

**Comment by notoriouslogank** [comment]
I like this.  Eventually, the bot *should* be smart enough to figure out that if you're running a MC Server, just running the !playing command itself should auto-gen the embed rather than you having to manually specify it. @Komorebiao

**Comment by Komorebiao** [comment]
roger roger

**Comment by notoriouslogank** [comment]
Gonna work on this next, I guess.

**Comment by notoriouslogank** [comment]
Done #25
